server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <your-client-id>
            client-secret: <your-client-secret>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            scope:
              - openid
              - profile
              - email
            client-name: Azure AD
            pkce:
              enabled: true
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me

  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://SERVICE1  # Change this based on your service registry (e.g., Eureka) or direct URI
          predicates:
            - Path=/service1/**

        - id: service2
          uri: lb://SERVICE2  # Same here, adjust as per your service registry
          predicates:
            - Path=/service2/**

      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
        - RemoveRequestHeader=X-Request-Foo


